### ISSUE TITLE
Update to fs-extra 11.+

### ISSUE THREAD

**Issue by AddictArts** [atao60/fse-cli#20]
## 🧩 Feature request

fs-extra recently updated 11.0.0 / 2022-11-28
See: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md

Should be as simple as updating the dependency, api has been kept the same.

**Comment by atao60** [comment]
In fact completed in 6418b7639364042cc0cb45d127c76b1e769484c3
