### ISSUE TITLE
1 high severity vulnerability

### ISSUE THREAD

**Issue by FreePhoenix888** [atao60/fse-cli#24]
### Description
1 high severity vulnerability
npm audit report

ansi-regex  5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw

#### 🔬 Minimal Reproduction
```
freephoenix888@freephoenix888:~/Programming/deep/create-typescript-npm-package-template$ npm i --save-dev @atao60/fse-cli

added 68 packages, and audited 139 packages in 10s

13 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```
```
freephoenix888@freephoenix888:~/Programming/deep/create-typescript-npm-package-template$ npm audit fix

up to date, audited 139 packages in 2s

13 packages are looking for funding
  run `npm fund` for details

npm audit report

ansi-regex  5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/@atao60/fse-cli/node_modules/ansi-regex

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```

#### 💻Your Environment

**Operating System:**

<pre><code>
Linux freephoenix888 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
</code></pre>

**Node.js Version:**
<pre><code>
v18.14.0
</code></pre>

**fse-cli Version:**
<pre><code>
0.1.7
</code></pre>

**Comment by atao60** [comment]
See 0.1.8+
