### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by ecpark-danbi** [atao60/fse-cli#5]
### Description

I'm using node version v12. so I got this error
```
error @atao60/fse-cli@0.0.25: The engine "node" is incompatible with this module. Expected version "10.15.3". Got "12.14.0"
error Found incompatible module.
```

### Describe the solution you'd like

Please provide various node version/

**Comment by atao60** [comment]
Thanks for trying  @atao60/fse-cli
Can to tell me more about your config? Which OS? How you install @atao60/fse-cli: globally? locally? npx?

**Comment by atao60** [comment]
@ecpark-danbi 
Can you test the last release 0.0.27?
I have been unable to reproduce the error you encountered. Did you set the 'engine-strict' config flag?

**Comment by ecpark-danbi** [comment]
> Thanks for trying @atao60/fse-cli
> Can you tell me more about your config? Which OS? How you install @atao60/fse-cli: globally? locally? npx?

I'm using MacOS Catalina 10.15.6, node version v12.14.0, and I tried this into my project (pakage.json: locally.
This error occurs in just installing this. I think this problem from your `package.json`'s `engine-version`

**Comment by ecpark-danbi** [comment]
Thank you. for fixing this. Now it work.

**Comment by atao60** [comment]
@ecpark-danbi Thanks for checking
> I think this problem from your package.json's engine-version

Yes but it's strange as the [doc](https://docs.npmjs.com/configuring-npm/package-json.html) states that:

> You can also use the “engines” field to specify which versions of npm are capable of properly installing your program. [...]
Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

Anyway I'm happy it's working now even on MacOS. I never had the opportunity to test it under OS X.
