### ISSUE TITLE
node_modules are added to npm release, adding 117MB

### ISSUE THREAD

**Issue by sschmidTU** [atao60/fse-cli#6]
### Description

the node_modules folder is unnecessarily added to the npm release of fse-cli, making up 117MB of the 118MB total package size. As a user of fse-cli, you certainly don't need eslint etc. packaged with this module.

#### 🔬 Minimal Reproduction

run npm install fse-cli [--save-dev]
check size of node_modules/@atao60/fse-cli/node_modules

#### 💻Your Environment

**fse-cli Version:**

0.0.29, also tested with 0.0.33

### Comments

I'm not sure why this isn't ignored for the npm release, because you have `node_modules/` added to your `.gitignore`, and according to [this](https://zellwk.com/blog/ignoring-files-from-npm-package/), npm releases should ignore all files in .gitignore (unless you have a .npmignore).
Maybe try changing `node_modules/` to `node_modules`?
In our project we have `node_modules/` and `node_modules/*` in the .gitignore.

Maybe you need to use a module system like webpack? There, you can definitely exclude the node_modules folder, and only package (and minify) the sources and builds necessary for running your module.

**Comment by atao60** [comment]
Thanks for trying @atao60/fse-cli.

Short story. Nothing to be done on @atao60/fse-cli side.

Long story short. Use `npm ci` in place of `npm install`.

Long story.

Neither .npmignore nor .gitignore are used by @atao60/fse-cli to "describe(..) the entries to be included when your package is installed as a dependency". But package.json#files is, cf. [npm docs - npm-package.json- files](https://docs.npmjs.com/files/package.json#files), i.e. here:
- the default ones: package.json, README.MD, CHANGELOG.md, USAGE, LICENCE (and ./dist/index.js but see below);
- the explicit ones from "package.json#files": bin/, dist/, MANUAL.md, CONTRIBUTING.md, npm-shrinkwrap.json

So to be clear, node_modules is **not** embedded in the package.

But as stated by [NPM docs - npm-install - Install a package](https://docs.npmjs.com/cli/install), `npm install` in target project will install any entry in `dependencies` ***and*** `devDependencies` of @atao60/fse-cli. Recursively!

Then running `pkgfiles` with `@atao60/fse-cli` gives:
- a Publishable Size of ~502 kB
- a Size with Dependencies of ~144 MB

Now the strange thing. Running `npm ll` in the target project gives:
```
[...]
npm ERR! extraneous: @babel/cli@7.11.5 /mnt/data/workspaces/npm-public-packages/test-size-fse-cli/node_modules/@atao60/fse-cli/node_modules/@babel/cli
npm ERR! extraneous: @babel/core@7.11.5 /mnt/data/workspaces/npm-public-packages/test-size-fse-cli/node_modules/@atao60/fse-cli/node_modules/@babel/core
npm ERR! extraneous: @babel/plugin-proposal-decorators@7.10.5 /mnt/data/workspaces/npm-public-packages/test-size-fse-cli/node_modules/@atao60/fse-cli/node_modules/@babel/plugin-proposal-decorators
npm ERR! extraneous: @babel/preset-env@7.11.5 /mnt/data/workspaces/npm-public-packages/test-size-fse-cli/node_modules/@atao60/fse-cli/node_modules/@babel/preset-env
npm ERR! extraneous: @babel/preset-typescript@7.10.4 /mnt/data/workspaces/npm-public-packages/test-size-fse-cli/node_modules/@atao60/fse-cli/node_modules/@babel/preset-typescript
[...]
```

but `npm purge` doesn't remove those "extraneous" packages. It seems it works only for depth 0.

To avoid installing "extraneous" packages, you can use `npm ci` or `npm ci --only=prod` in place of `npm install`.

Or to remove them manually or with a dedicated script, in both cases based on the output of `npm ll`.

Then the size of node_modules/@atao60/fse-cli folder has shrunk to 40 Mo.

Any other idea will be welcome. So I'll keep this issue open for some time.

**Comment by atao60** [comment]
Reopening: will try with an embedded npm-shrinkwrap.json expunged from dev deps.
